CREATE TABLE IF NOT EXISTS payment_reconcile_issue (
    issue_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '支付对账异常主键',
    payment_request_id VARCHAR(64) NOT NULL COMMENT '支付请求标识',
    order_id BIGINT NOT NULL COMMENT '订单标识',
    order_no VARCHAR(64) NOT NULL COMMENT '订单编号',
    reservation_id VARCHAR(64) NOT NULL COMMENT '预扣标识',
    user_id BIGINT NOT NULL COMMENT '用户标识',
    activity_id BIGINT NOT NULL COMMENT '活动标识',
    ticket_id BIGINT NOT NULL COMMENT '票种标识',
    quantity INT NOT NULL COMMENT '购买数量',
    payment_status VARCHAR(32) NOT NULL COMMENT '支付状态',
    order_status VARCHAR(32) DEFAULT NULL COMMENT '订单状态',
    issue_type VARCHAR(64) NOT NULL COMMENT '异常类型',
    issue_status VARCHAR(32) NOT NULL COMMENT '异常状态',
    latest_error_message VARCHAR(255) DEFAULT NULL COMMENT '最近错误信息',
    first_detected_at DATETIME NOT NULL COMMENT '首次发现时间',
    last_detected_at DATETIME NOT NULL COMMENT '最近发现时间',
    resolved_at DATETIME DEFAULT NULL COMMENT '解决时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_payment_reconcile_issue_payment_request_id (payment_request_id),
    KEY idx_payment_reconcile_issue_order_id (order_id),
    KEY idx_payment_reconcile_issue_issue_status (issue_status)
) COMMENT='支付对账异常事实表';
